baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'William Kye'
theme = "beautifulhugo"
[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Build a beautiful and simple website in minutes"
