baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'William Kye'
theme = 'hugo-theme-mini'
enableEmoji = true

[Params]
    headline = "William Kye"
    logoBig = "/images/profile_pic.jpg"
