baseURL = 'https://incandescent-tiramisu-b11fae.netlify.app'
languageCode = 'en-us'
title = 'William Kye'
theme = 'hugo-theme-mini'
enableEmoji = true

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[Params]
    headline = "William Kye"
    subBio = """Willie is a data enthusiast based in NYC. Formerly in a Ph.D. program
    at the University of Notre Dame, he is technically trained as a social scientist
    but really just a problem solver at heart. Currently a data scientist at [clockwise](getclockwise.com])
    where he is the data czar of all things money related (stripe, growth, revenue,
    etc. you get the picture). Willie still finds speaking in 3rd person to be
    uncomfortable.
    <br>
    <br>
    If you wanna connect or just say hi, please reach out williamkye93[at]gmail[dot]com
    """
    github = "https://github.com/wkye"
    linkedin = "https://www.linkedin.com/in/william-kye-33251a114/"
    twitter = "https://twitter.com/William_Kye"

[permalinks]
  posts = "/blog/:title/"
